### ISSUE TITLE
Valet share does not use the "normal" ngrok config location by default?

### ISSUE THREAD

**Issue by IvaWonderbush** [laravel/valet#904]
I'm trying to setup config of ngrok in `~/.ngrok2/ngrok.yml` seeing as this is the _"normal"_ way of doing it per [ngrok documentation](https://ngrok.com/docs#config-default-location). Yet it seems Valet does not use this config when running `valet share`

Does Valet share even use a config without having to pass it via the command option and if so where is it located? I don't really want to specify the config option each time I use valet share.

**Comment by drbyte** [comment]
Mine is located at `~/.ngrok2/ngrok.yml` and is loaded correctly whenever I run `valet share`.
... and contains the following few simple settings.

I know it works because the authtoken recognizes and displays my account name whenever I run `valet share`.

```yml
authtoken: (redacted of course)

#docs: https://ngrok.com/docs

json_resolver_url: ""
dns_resolver_ips: []

# root_cas options: trusted, host, or path-to-a-CA-file
root_cas: trusted

# auto-update
update: true
```
